# Use uma imagem base Python
FROM python:3.9-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o requirements.txt e instale as dependências
COPY ../scripts/requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copie o script Python
COPY ../src/etl_bacen.py .

# Comando para executar o script
CMD ["python", "etl_bacen.py"]
