# dump build stage
FROM postgres:13-alpine as dumper

COPY /scripts/postgres/init.sql /docker-entrypoint-initdb.d/

# para cancelar a execução padrão
RUN ["sed", "-i", "s/exec \"$@\"/echo \"skipping...\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV PG_USER=postgres
# ENV PGDATA=/data
ENV PGDATA=/var/lib/postgresql/data

RUN ["/usr/local/bin/docker-entrypoint.sh", "root"]

# final build stage
FROM postgres:13-alpine

COPY --from=dumper /var/lib/postgresql/data $PGDATA